version: '3.9'

services:
  db:
    ports:
      - 5432:5432
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chiaki_nanami
