import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ['700', '500', '400'], subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={'border-b-2 border-gray-500 border-solid ' + roboto.className}>
          <div className='max-w-screen-lg mx-auto p-8'>
            <Link href='/posts'>
              <h1 className='font-medium text-2xl'>
                ProtesteAqui
              </h1>
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
